"""
agentevals — Evals agent based on agent-skill architecture.

Evaluate responses generated by other AI agents using composable skills.

Quick start::

    from agentevals import EvalsAgent, EvalInput
    from agentevals.skills import (
        CorrectnessSkill,
        RelevanceSkill,
        CoherenceSkill,
        FaithfulnessSkill,
        ConcisenessSkill,
    )

    agent = EvalsAgent(
        skills=[
            CorrectnessSkill(),
            RelevanceSkill(),
            CoherenceSkill(),
            FaithfulnessSkill(),
            ConcisenessSkill(),
        ]
    )

    result = agent.evaluate(
        EvalInput(
            question="What is the capital of France?",
            response="The capital of France is Paris.",
            reference="Paris is the capital city of France.",
        )
    )

    print(result.overall_score)   # e.g. 0.95
    print(result.passed)          # True / False
"""

from agentevals.agent import EvalsAgent
from agentevals.models import EvalInput, EvalResult, SkillResult

__all__ = [
    "EvalsAgent",
    "EvalInput",
    "EvalResult",
    "SkillResult",
]
