"""EvalsAgent — the main orchestrator that runs evaluation skills."""

from __future__ import annotations

from typing import Sequence

from agentevals.models import EvalInput, EvalResult, SkillResult
from agentevals.skills.base import BaseSkill


class EvalsAgent:
    """Orchestrates a collection of :class:`~agentevals.skills.base.BaseSkill` objects
    to evaluate a response generated by another agent.

    Example usage::

        from agentevals import EvalsAgent, EvalInput
        from agentevals.skills import (
            CorrectnessSkill,
            RelevanceSkill,
            CoherenceSkill,
            FaithfulnessSkill,
            ConcisenessSkill,
        )

        agent = EvalsAgent(
            skills=[
                CorrectnessSkill(),
                RelevanceSkill(),
                CoherenceSkill(),
                FaithfulnessSkill(),
                ConcisenessSkill(),
            ]
        )

        result = agent.evaluate(
            EvalInput(
                question="What is the capital of France?",
                response="The capital of France is Paris.",
                reference="Paris is the capital city of France.",
            )
        )

        print(result.overall_score)   # e.g. 0.9
        print(result.passed)          # True

    Args:
        skills: Ordered list of :class:`~agentevals.skills.base.BaseSkill` instances.
            Skills are run in the order they are provided.  An empty skill list is
            allowed (returns a default :class:`~agentevals.models.EvalResult`).
        stop_on_failure: When ``True``, stop executing skills as soon as one skill
            returns ``passed=False``.  Defaults to ``False`` (run all skills).
    """

    def __init__(
        self,
        skills: Sequence[BaseSkill] | None = None,
        *,
        stop_on_failure: bool = False,
    ) -> None:
        self.skills: list[BaseSkill] = list(skills or [])
        self.stop_on_failure = stop_on_failure

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def evaluate(self, eval_input: EvalInput) -> EvalResult:
        """Run all registered skills against *eval_input* and return an
        :class:`~agentevals.models.EvalResult` with aggregated scores.

        Args:
            eval_input: The bundled question/response/reference/context to evaluate.

        Returns:
            An :class:`~agentevals.models.EvalResult` containing individual
            :class:`~agentevals.models.SkillResult` objects and an aggregated
            ``overall_score``.
        """
        skill_results: list[SkillResult] = []

        for skill in self.skills:
            result = skill.evaluate(eval_input)
            skill_results.append(result)

            if self.stop_on_failure and not result.passed:
                break

        eval_result = EvalResult(
            skill_results=skill_results,
            summary=self._build_summary(skill_results),
        )
        return eval_result

    def add_skill(self, skill: BaseSkill) -> "EvalsAgent":
        """Append a skill to the agent and return ``self`` for chaining.

        Args:
            skill: The :class:`~agentevals.skills.base.BaseSkill` to add.

        Returns:
            This :class:`EvalsAgent` instance (fluent API).
        """
        self.skills.append(skill)
        return self

    def remove_skill(self, skill_name: str) -> "EvalsAgent":
        """Remove a skill by name and return ``self`` for chaining.

        Args:
            skill_name: The :attr:`~agentevals.skills.base.BaseSkill.name` of the
                skill to remove.

        Returns:
            This :class:`EvalsAgent` instance (fluent API).
        """
        self.skills = [s for s in self.skills if s.name != skill_name]
        return self

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _build_summary(skill_results: list[SkillResult]) -> str:
        if not skill_results:
            return "No skills were run."

        passed = sum(1 for r in skill_results if r.passed)
        total = len(skill_results)
        avg = sum(r.score for r in skill_results) / total
        status = "PASSED" if passed == total else "FAILED"
        return (
            f"{status}: {passed}/{total} skills passed "
            f"(overall_score={avg:.2f})"
        )
