"""Data models used throughout agentevals."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, model_validator


class EvalInput(BaseModel):
    """Input bundle passed to the evals agent and each skill.

    Attributes:
        question: The question / prompt that was given to the agent under evaluation.
        response: The response generated by the agent under evaluation.
        reference: (optional) Ground-truth / expected answer. Required by skills
            that measure correctness.
        context: (optional) Source documents or context that the agent was expected
            to use. Required by skills that measure faithfulness / grounding.
        metadata: Arbitrary extra data (e.g. conversation history, tool calls).
    """

    question: str = Field(..., description="The question asked of the agent.")
    response: str = Field(..., description="The agent's response to evaluate.")
    reference: str | None = Field(
        default=None,
        description="Ground-truth answer (used by CorrectnessSkill).",
    )
    context: str | None = Field(
        default=None,
        description="Source context the agent should have used (used by FaithfulnessSkill).",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Optional extra data to pass through to skills.",
    )


class SkillResult(BaseModel):
    """Result produced by a single evaluation skill.

    Attributes:
        skill_name: Name of the skill that produced this result.
        score: Float in [0, 1] where 1.0 is the best possible score.
        passed: Whether the skill considers the response acceptable
            (score >= threshold).
        reasoning: Human-readable explanation of the score.
        details: Any extra structured data the skill wants to expose.
    """

    skill_name: str
    score: float = Field(..., ge=0.0, le=1.0)
    passed: bool
    reasoning: str = ""
    details: dict[str, Any] = Field(default_factory=dict)


class EvalResult(BaseModel):
    """Aggregated result returned by :class:`~agentevals.agent.EvalsAgent`.

    Attributes:
        skill_results: Individual results from each skill that ran.
        overall_score: Mean of all skill scores.
        passed: ``True`` when *every* skill reports ``passed=True``.
        summary: One-line human-readable summary.
    """

    skill_results: list[SkillResult] = Field(default_factory=list)
    overall_score: float = Field(default=0.0, ge=0.0, le=1.0)
    passed: bool = False
    summary: str = ""

    @model_validator(mode="after")
    def _compute_aggregates(self) -> "EvalResult":
        if self.skill_results:
            self.overall_score = round(
                sum(r.score for r in self.skill_results) / len(self.skill_results), 4
            )
            self.passed = all(r.passed for r in self.skill_results)
        return self

    def skill(self, name: str) -> SkillResult | None:
        """Return the :class:`SkillResult` for the skill with the given name."""
        for result in self.skill_results:
            if result.skill_name == name:
                return result
        return None
